window.STONE_CONSTANTS = Object.freeze({
  TYPE_N: Object.freeze({
    bk_2: 2,
    bk_4h: 4,
    bk_6h: 6,
    bk_6v: 6,
    pk_4h: 4,
    pk_6h: 6,
    pk_4v: 4,
    pk_6v: 6,
  }),
  ANC_SPECS: Object.freeze({
    '3/8"': Object.freeze({ label: '3/8" 內迫型膨脹螺栓', d0: 1.2 }),
    '1/2"': Object.freeze({ label: '1/2" 內迫型膨脹螺栓', d0: 1.6 }),
    M8: Object.freeze({ label: 'M8 化學錨栓', d0: 1.0 }),
    M10: Object.freeze({ label: 'M10 化學錨栓', d0: 1.2 }),
    M12: Object.freeze({ label: 'M12 化學錨栓', d0: 1.4 }),
    custom: Object.freeze({ label: '自訂', d0: null }),
  }),
  ANCHOR_CATALOG: Object.freeze({
    custom: Object.freeze({
      label: '自訂（手動輸入）',
      d: '',
      D: '',
      holeMm: null,
      embedMm: null,
      lengthMm: null,
      torqueNm: null,
      Nu: null,
      Vu: null,
    }),
    'SH-440': Object.freeze({
      label: 'SH-440（d=1/2"）',
      d: '1/2"',
      D: '11/16"',
      holeMm: 17.5,
      embedMm: 50.8,
      lengthMm: 75,
      torqueNm: 24,
      Nu: Object.freeze({ 210: 2800, 280: 3700 }),
      Vu: Object.freeze({ 210: 3000, 280: 3000 }),
    }),
    'SH-550': Object.freeze({
      label: 'SH-550（d=5/8"）',
      d: '5/8"',
      D: '7/8"',
      holeMm: 22.2,
      embedMm: 63.5,
      lengthMm: 90,
      torqueNm: 38,
      Nu: Object.freeze({ 210: 3850, 280: 5200 }),
      Vu: Object.freeze({ 210: 4600, 280: 5100 }),
    }),
    'SH-560': Object.freeze({
      label: 'SH-560（d=5/8"，加長型）',
      d: '5/8"',
      D: '7/8"',
      holeMm: 22.2,
      embedMm: 63.5,
      lengthMm: 100,
      torqueNm: 38,
      Nu: Object.freeze({ 210: 3850, 280: 5200 }),
      Vu: Object.freeze({ 210: 4600, 280: 5100 }),
    }),
    'SH-660': Object.freeze({
      label: 'SH-660（d=3/4"）',
      d: '3/4"',
      D: '1"',
      holeMm: 26.0,
      embedMm: 76.2,
      lengthMm: 110,
      torqueNm: 62,
      Nu: Object.freeze({ 210: 5700, 280: 5700 }),
      Vu: Object.freeze({ 210: 7200, 280: 7200 }),
    }),
  }),
  ANCHOR_FC_OPTIONS: Object.freeze([210, 280]),
  ANCHOR_SF_OPTIONS: Object.freeze([3, 4, 5, 8, 10]),
  ANCHOR_DEFAULT_TYPE: 'custom',
  ANCHOR_DEFAULT_FC: 280,
  ANCHOR_DEFAULT_SF: 5,
  TYPE_LABEL: Object.freeze({
    bk_2: '背扣孔─上下各1點',
    bk_4h: '背扣孔─上下各2點',
    bk_6h: '背扣孔─上下各3點',
    bk_6v: '背扣孔─左右各3點',
    pk_4h: '插銷式─上下各2支',
    pk_6h: '插銷式─上下各3支',
    pk_4v: '插銷式─左右各2支',
    pk_6v: '插銷式─左右各3支',
  }),
  MATERIAL_GRADE_OPTIONS: Object.freeze([
    Object.freeze({ value: 'sus304', label: 'SUS304', approved: true }),
    Object.freeze({ value: 'sus316', label: 'SUS316', approved: true }),
    Object.freeze({ value: 'astm_a123', label: 'ASTM-A123 熱浸鍍鋅', approved: true }),
    Object.freeze({ value: 'other', label: '其他', approved: false }),
  ]),
  PANEL_MODE_OPTIONS: Object.freeze([
    Object.freeze({ value: 'two_way_rankine', label: '雙向 Rankine-Grashof 載重分配' }),
    Object.freeze({ value: 'one_way_short', label: '單向短邊簡支' }),
    Object.freeze({ value: 'one_way_long', label: '單向長邊簡支' }),
  ]),
  PANEL_LOCAL_MODE_OPTIONS: Object.freeze([
    Object.freeze({ value: 'auto', label: '自動（背擴孔採錐形／插梢採孔周剪應力）' }),
    Object.freeze({ value: 'ring', label: '孔周剪應力（簡化）' }),
    Object.freeze({ value: 'cone', label: '背擴孔錐形拉出（角度可調）' }),
  ]),
  PANEL_CONE_ANGLE_OPTIONS: Object.freeze([
    Object.freeze({ value: 20, label: '20°（較脆性）' }),
    Object.freeze({ value: 30, label: '30°（花崗岩常用）' }),
    Object.freeze({ value: 45, label: '45°（需試驗佐證）' }),
  ]),
  ANGLE_SECTION_OPTIONS: Object.freeze([
    Object.freeze({ value: 'rect_plate', label: '矩形板近似' }),
    Object.freeze({ value: 'l_angle_composite', label: 'L 型角鋼合成斷面' }),
  ]),
  STONE_GRADE_CATALOG: Object.freeze({
    custom: Object.freeze({
      label: '自訂試驗值',
      fb: 55,
      ft: 35,
      sf: 5,
      source: '依專案試驗報告或指定值輸入',
    }),
    granite_grade1: Object.freeze({
      label: '花崗岩（一級）',
      fb: 70,
      ft: 45,
      sf: 5,
      source: 'CNS 14448 / CNS 6300 A1028 試驗值整理',
    }),
    granite_grade2: Object.freeze({
      label: '花崗岩（二級）',
      fb: 55,
      ft: 35,
      sf: 5,
      source: 'CNS 14448 / CNS 6300 A1028 試驗值整理',
    }),
    marble: Object.freeze({
      label: '大理石',
      fb: 35,
      ft: 22,
      sf: 5,
      source: 'CNS 14448 / CNS 6300 A1028 試驗值整理',
    }),
    sandstone: Object.freeze({
      label: '砂岩',
      fb: 22,
      ft: 14,
      sf: 5,
      source: 'CNS 14448 / CNS 6300 A1028 試驗值整理',
    }),
  }),
  PSI_CV: Object.freeze({
    none: 1.0,
    edge_rebar: 1.2,
    full_rebar: 1.4,
  }),
  PSI_CN: Object.freeze({
    cracked: 1.0,
    noncracked: 1.25,
  }),
  PSI_CV_LABEL: Object.freeze({
    none: '無邊緣輔助鋼筋',
    edge_rebar: '邊緣輔助鋼筋',
    full_rebar: '完整邊緣輔助鋼筋',
  }),
  GEOMETRY_RULE_OPTIONS: Object.freeze([
    Object.freeze({ value: 'combined', label: '兩者並聯（較嚴）' }),
    Object.freeze({ value: 'draft', label: '規範研擬本' }),
    Object.freeze({ value: 'taipei', label: '台北市規範' }),
  ]),
  ACI_CATEGORY_OPTIONS: Object.freeze([
    Object.freeze({ value: 1, label: 'Category 1（完整認證，未開裂 ψc,N = 1.25）' }),
    Object.freeze({ value: 2, label: 'Category 2（未開裂 ψc,N = 1.00）' }),
    Object.freeze({ value: 3, label: 'Category 3（未開裂 ψc,N = 1.00）' }),
  ]),
  DRIFT_SPAN_OPTIONS: Object.freeze([
    Object.freeze({ value: 'single_story', label: '單層內石材（以板高估算）' }),
    Object.freeze({ value: 'multi_story', label: '跨層石材（以層高估算）' }),
  ]),
  SPEC_MODULES: Object.freeze({
    sp_anchor_on: Object.freeze({ title: 'A1 錨栓雙軌設計', defaultOn: true }),
    sp_bk2_on: Object.freeze({ title: 'A2 兩點固定警語', defaultOn: true }),
    sp_panel_on: Object.freeze({ title: 'B1 石材板塊檢核', defaultOn: true }),
    sp_psicv_on: Object.freeze({ title: 'B2 開裂混凝土 ψc,V', defaultOn: true }),
    sp_geometry_on: Object.freeze({ title: 'B3 孔位幾何規則', defaultOn: true }),
    sp_custom_anchor_on: Object.freeze({ title: 'B4 錨栓／插梢最小尺寸檢核', defaultOn: true }),
    sp_material_on: Object.freeze({ title: 'B5 材質強制要求', defaultOn: true }),
    sp_dimension_on: Object.freeze({ title: 'B6 厚度與面積限制', defaultOn: true }),
    sp_wind_dir_on: Object.freeze({ title: 'C1 負風壓方向性', defaultOn: true }),
    sp_ip15_on: Object.freeze({ title: 'C2 Ip 預設 1.5', defaultOn: true }),
    sp_chapter_on: Object.freeze({ title: 'C3 報告章節重排', defaultOn: true }),
    sp_torque_on: Object.freeze({ title: 'C4 扭力施工記錄', defaultOn: true }),
    sp_angle_on: Object.freeze({ title: 'C5 L 型角鋼斷面模數', defaultOn: true }),
    sp_seismic_detail_on: Object.freeze({ title: 'C6 耐震細算', defaultOn: true }),
    sp_anchor_group_on: Object.freeze({ title: 'C7 錨栓群組／邊距折減', defaultOn: true }),
    sp_drift_on: Object.freeze({ title: 'C8 層間變位檢核', defaultOn: true }),
    sp_thermal_on: Object.freeze({ title: 'C9 溫度伸縮／伸縮縫估算', defaultOn: true }),
  }),
  FIELD_RULES: Object.freeze({
    w_v: Object.freeze({
      label: '設計風速 V',
      min: 26,
      max: 40,
      message: '應介於 26～40 m/s。',
    }),
    s_sds: Object.freeze({
      label: 'SDS',
      min: 0,
      max: 3,
      message: '應介於 0.00～3.00。',
    }),
    cc_kzt: Object.freeze({
      label: '地形係數 Kzt',
      min: 1,
      max: 3,
      message: '應介於 1.00～3.00。',
    }),
    w_qref: Object.freeze({
      label: '參考風壓 q',
      min: 10,
      max: 500,
      message: '應介於 10～500 kgf/m²。',
    }),
    w_cpe_pos: Object.freeze({
      label: '外壓係數 Cpe(+)',
      min: 0,
      max: 3,
      message: '應介於 0.00～3.00。',
    }),
    w_cpe_neg: Object.freeze({
      label: '外壓係數 Cpe(-)',
      min: -5,
      max: 0,
      message: '應介於 -5.00～0.00。',
    }),
    w_gcpi: Object.freeze({
      label: '內壓係數 GCpi',
      min: 0,
      max: 1,
      message: '應介於 0.00～1.00。',
    }),
    sp_drift_theta: Object.freeze({
      label: '層間變位角 θa',
      min: 0.002,
      max: 0.02,
      message: '應介於 0.002～0.020。',
    }),
    sp_story_height_mm: Object.freeze({
      label: '參考層高 hs',
      min: 2500,
      max: 6000,
      message: '應介於 2500～6000 mm。',
    }),
    sp_thermal_alpha: Object.freeze({
      label: '線膨脹係數 α',
      min: 0.000004,
      max: 0.000012,
      message: '應介於 4×10⁻⁶～12×10⁻⁶ /°C。',
    }),
    sp_thermal_delta_t: Object.freeze({
      label: '設計溫差 ΔT',
      min: 10,
      max: 80,
      message: '應介於 10～80 °C。',
    }),
    sp_thermal_reserve_mm: Object.freeze({
      label: '施工／封膠預留 r',
      min: 0,
      max: 15,
      message: '應介於 0～15 mm。',
    }),
  }),
  SPEC_REFS: Object.freeze({
    cc: '建築物耐風設計規範及解說（107 年版）',
    seismic: '建築物耐震設計規範及解說（113 年版）',
    anchor: '混凝土結構設計規範附篇 D「混凝土結構用錨栓」＋ 廠商 ETA／ACI 355.2 試驗報告',
    steel: '鋼構造建築物鋼結構設計技術規範（容許應力設計法）',
    stone: 'CNS 14448、CNS 6300 A1028 試驗值與日本 JASS 9 常用安全係數',
    geometry: '石材外牆規範研擬本 2.1.5 / 2.1.8 / 3.2.4 及台北市石材外牆作業規範 2.1.6 / 2.1.7 / 2.2.3 / 2.2.4',
    drift: '建築物耐震設計規範及解說（113 年版）§13.5.2 非結構組件層間變位要求',
    thermal: '石材線膨脹係數常用值（花崗岩約 8×10⁻⁶/°C）與伸縮縫配置實務估算',
  }),
  COMMON_PRESETS: Object.freeze({
    stone_30_back4: Object.freeze({
      label: '30mm 石材＋背扣 4 點',
      stoneThicknessMm: 30,
      caseType: 'bk_4h',
      connectionSpec: 'M8 不鏽鋼背扣螺絲',
      anchorSpec: '3/8"',
      materialGrade: 'sus304',
    }),
    stone_30_pin4: Object.freeze({
      label: '30mm 石材＋插銷 4 點',
      stoneThicknessMm: 30,
      caseType: 'pk_4h',
      connectionSpec: 'ψ4mm 不鏽鋼插銷',
      anchorSpec: '3/8"',
      materialGrade: 'sus304',
    }),
  }),
});
