window.StoneFormulaRegistry = Object.freeze({
  VERSION: 'formula-registry-2026.04.25',
  refs: Object.freeze({
    cc: '建築物耐風設計規範及解說（107 年版）',
    seismic: '建築物耐震設計規範及解說（113 年版）',
    anchor: '混凝土結構設計規範附篇 D「混凝土結構用錨栓」及廠商試驗資料',
    steel: '鋼構造建築物鋼結構設計技術規範（容許應力設計法）',
    stone: 'CNS 14448、CNS 6300 A1028 與 JASS 9 常用安全係數',
    geometry: '石材外牆規範研擬本與台北市石材外牆作業規範之孔位幾何要求',
    drift: '建築物耐震設計規範及解說（113 年版）非結構組件層間變位要求',
    thermal: '石材線膨脹係數常用值與伸縮縫配置實務估算',
  }),
  checks: Object.freeze({
    '膨脹螺栓 Tu1（垂直力）': Object.freeze({ category: 'anchor', formula: 'Tu1 = V × h ÷ d1', unit: 'kgf', ref: 'anchor' }),
    '膨脹螺栓 Tu2（水平力）': Object.freeze({ category: 'anchor', formula: 'Tu2 = T × h ÷ d1', unit: 'kgf', ref: 'anchor' }),
    '膨脹螺栓 剪力': Object.freeze({ category: 'anchor', formula: 'Vanc = V', unit: 'kgf', ref: 'anchor' }),
    '膨脹螺栓 拉剪交互': Object.freeze({ category: 'anchor', formula: 'R = (Tu/Ta)^1.67 + (V/Va)^1.67 <= 1.0', unit: '', ref: 'anchor' }),
    '背扣螺絲 抗拔': Object.freeze({ category: 'back_anchor', formula: 'T = P / N', unit: 'kgf', ref: 'anchor' }),
    '馬車螺栓 剪力': Object.freeze({ category: 'back_anchor', formula: 'V = T', unit: 'kgf', ref: 'anchor' }),
    '馬車螺栓 拉力 T₁': Object.freeze({ category: 'back_anchor', formula: 'T1 = V × h1 / h2', unit: 'kgf', ref: 'anchor' }),
    '插銷 剪力': Object.freeze({ category: 'pin', formula: 'Tu <= Va', unit: 'kgf', ref: 'stone' }),
    '角鋼 剪力（淨截面）': Object.freeze({ category: 'steel', formula: 'V <= 0.4 × Fy × Au', unit: 'kgf', ref: 'steel' }),
    '角鋼 彎矩（斷面模數）': Object.freeze({ category: 'steel', formula: 'Sreq = M / Fb', unit: 'cm3', ref: 'steel' }),
    '石材板彎曲應力': Object.freeze({ category: 'stone_panel', formula: 'fb = m / Z', unit: 'kgf/cm2', ref: 'stone' }),
    '石材孔周剪應力 / 石板衝切（簡化）': Object.freeze({ category: 'stone_local', formula: 'sigma = T / (pi × d × t_net)', unit: 'kgf/cm2', ref: 'stone' }),
    '石材背擴孔錐形拉出 / 石板衝切（30°簡化）': Object.freeze({ category: 'stone_local', formula: 'sigma = T / A_cone', unit: 'kgf/cm2', ref: 'stone' }),
    '掛件相對位移容許': Object.freeze({ category: 'drift', formula: 'delta = theta_a × h <= Delta_allow', unit: 'mm', ref: 'drift' }),
    '掛件轉角容許': Object.freeze({ category: 'drift', formula: 'theta_a <= theta_allow', unit: 'deg', ref: 'drift' }),
    '伸縮縫淨寬估算': Object.freeze({ category: 'thermal', formula: 'g >= alpha × DeltaT × L + r', unit: 'mm', ref: 'thermal' }),
    '插梢孔邊距': Object.freeze({ category: 'geometry', formula: '50 <= e <= 0.25 × panel dimension', unit: 'mm', ref: 'geometry' }),
    '插梢孔深度': Object.freeze({ category: 'geometry', formula: '20 <= h <= 30', unit: 'mm', ref: 'geometry' }),
    '背擴孔邊距': Object.freeze({ category: 'geometry', formula: '60 <= e <= 300 and e <= 0.25 × panel dimension', unit: 'mm', ref: 'geometry' }),
    '背擴孔間距': Object.freeze({ category: 'geometry', formula: 's <= 800', unit: 'mm', ref: 'geometry' }),
    '背擴孔深度': Object.freeze({ category: 'geometry', formula: '12 <= h <= 38 and h <= 0.4t', unit: 'mm', ref: 'geometry' }),
    '石材厚度限制': Object.freeze({ category: 'dimension', formula: 't >= 30', unit: 'mm', ref: 'stone' }),
    '單片面積限制': Object.freeze({ category: 'dimension', formula: 'A <= 1.0', unit: 'm2', ref: 'stone' }),
    '金屬支撐材質': Object.freeze({ category: 'material', formula: 'approved material grade check', unit: '', ref: 'steel' }),
    '自訂錨栓長度': Object.freeze({ category: 'anchor_geometry', formula: 'L >= 75', unit: 'mm', ref: 'anchor' }),
    '自訂錨栓埋深': Object.freeze({ category: 'anchor_geometry', formula: 'hef >= 40', unit: 'mm', ref: 'anchor' }),
    '自訂錨栓邊距': Object.freeze({ category: 'anchor_geometry', formula: 'c >= 25', unit: 'mm', ref: 'anchor' }),
    '自訂錨栓直徑': Object.freeze({ category: 'anchor_geometry', formula: 'd >= 4', unit: 'mm', ref: 'anchor' }),
    '插梢鋼棒長度': Object.freeze({ category: 'pin_geometry', formula: 'L >= 75', unit: 'mm', ref: 'stone' }),
    '插梢鋼棒埋深': Object.freeze({ category: 'pin_geometry', formula: 'hef >= 40', unit: 'mm', ref: 'stone' }),
    '插梢鋼棒邊距': Object.freeze({ category: 'pin_geometry', formula: 'c >= 25', unit: 'mm', ref: 'stone' }),
    '插梢鋼棒直徑': Object.freeze({ category: 'pin_geometry', formula: 'd >= 4', unit: 'mm', ref: 'stone' }),
  }),
});
