const fs = require('node:fs'), path = require('node:path');
const root = __dirname;
const HTML = fs.readFileSync(path.join(root, 'index.html'), 'utf8'), CLIENT = fs.readFileSync(path.join(root, 'client.js'), 'utf8');
fs.writeFileSync(path.join(root, 'assets.js'), `// Generated by build.cjs.\nexport const HTML=${JSON.stringify(HTML)};\nexport const CLIENT=${JSON.stringify(CLIENT)};\n`);
