import type {
  AnchorProduct,
  ProjectCase,
  ReportSettings,
  RuleProfile,
} from './domain'
import { defaultLoadCasePresetInput } from './loadCasePresetInput'
import { defaultUnitPreferences } from './units'

export const defaultReportSettings: ReportSettings = {
  companyName: '',
  projectCode: '',
  designer: '',
  checker: '',
  issueDate: '',
  reportMode: 'full',
}

export function normalizeReportSettings(
  settings?: Partial<ReportSettings>,
): ReportSettings {
  return {
    ...defaultReportSettings,
    ...settings,
  }
}

export const twRc112AnchorProfile: RuleProfile = {
  id: 'tw_rc_112_anchor_profile',
  name: '台灣《建築物混凝土結構設計規範》112年版',
  versionLabel: '112年版 / 113年1月1日生效',
  officialPublishedDate: '2023-08-10',
  effectiveDate: '2024-01-01',
  errataDate: '2024-02-19',
  officialUrl: 'https://www.nlma.gov.tw/ch/legislation/regsearch/6874',
  chapter17Url:
    'https://www.nlma.gov.tw/uploads/files/011d9249cac7d6c5547786aa348e352a.pdf',
  chapter17Title: '第17章 混凝土結構用錨栓',
  citations: {
    steelTension: {
      chapter: '17',
      clause: '17.6.1',
      title: '拉力鋼材強度',
    },
    concreteBreakoutTension: {
      chapter: '17',
      clause: '17.6.2',
      title: '混凝土拉破強度',
    },
    pullout: {
      chapter: '17',
      clause: '17.6.3',
      title: '拉出破壞強度',
    },
    sideFaceBlowout: {
      chapter: '17',
      clause: '17.6.4',
      title: '側面破裂強度',
    },
    bond: {
      chapter: '17',
      clause: '17.6.5',
      title: '握裹強度',
    },
    steelShear: {
      chapter: '17',
      clause: '17.7.1',
      title: '剪力鋼材強度',
    },
    concreteBreakoutShear: {
      chapter: '17',
      clause: '17.7.2',
      title: '混凝土剪破強度',
    },
    pryout: {
      chapter: '17',
      clause: '17.7.3',
      title: '撬出強度',
    },
    interaction: {
      chapter: '17',
      clause: '17.8',
      title: '拉力和剪力互制作用',
    },
    minimumDimensions: {
      chapter: '17',
      clause: '17.9',
      title: '避免劈裂破壞之邊距、間距和厚度需求',
    },
    seismic: {
      chapter: '17',
      clause: '17.10',
      title: '錨栓耐震設計需求',
    },
    shearLug: {
      chapter: '17',
      clause: '17.11',
      title: '具剪力榫之基板',
    },
    supportBearing: {
      chapter: '22',
      clause: '22.8.3',
      title: '支承強度',
      note: '基板下混凝土承壓延伸檢核，φ=0.65 由規範 profile 固定提供。',
    },
  },
  constants: {
    lambdaA: 1,
    kcCastIn: 10,
    kcPostInstalled: 7,
    shearConstantA: 0.6,
    shearConstantB: 3.7,
    sideFaceBlowoutConstant: 13,
    pryoutThresholdMm: 65,
  },
  phi: {
    steelTension: 0.75,
    steelShear: 0.65,
    castInConcrete: 0.7,
    postInstalledConcrete: 0.65,
    concreteWithSupplementaryReinforcement: 0.75,
    bearingCompression: 0.65,
  },
}

export const defaultProducts: AnchorProduct[] = [
  {
    id: 'generic-cast-m20',
    family: 'cast_in',
    installationBehavior: 'not_torqued',
    brand: 'Generic',
    model: 'Cast-in Headed M20',
    description: '預埋擴頭錨栓範例，適合作為第17章基本流程起點。',
    diameterMm: 20,
    effectiveAreaMm2: 245,
    embedmentMinMm: 100,
    embedmentMaxMm: 500,
    steelYieldStrengthMpa: 400,
    steelUltimateStrengthMpa: 620,
    headBearingAreaMm2: 804,
    evaluation: {},
    source: '工具內建通用範例',
    notes: '預埋錨栓不依賴後置產品評估資料，可直接做正式規範檢核。',
  },
  {
    id: 'template-expansion-m16',
    family: 'post_installed_expansion',
    installationBehavior: 'torque_controlled',
    brand: 'Template',
    model: 'Expansion Anchor M16',
    description: '後置膨脹錨栓模板。請以產品評估報告補齊 cmin / smin / pullout 等數值。',
    diameterMm: 16,
    effectiveAreaMm2: 157,
    embedmentMinMm: 65,
    embedmentMaxMm: 160,
    steelYieldStrengthMpa: 500,
    steelUltimateStrengthMpa: 650,
    evaluation: {
      qualificationStandard: undefined,
    },
    source: '工具內建模板',
    notes: '未填入產品評估值前，工具只提供初篩與幾何檢核，不顯示正式通過。',
  },
  {
    id: 'template-bonded-m16',
    family: 'post_installed_bonded',
    installationBehavior: 'bonded',
    brand: 'Template',
    model: 'Bonded Anchor M16',
    description: '後置黏結式錨栓模板。請填入握裹強度、臨界邊距與產品最小尺寸。',
    diameterMm: 16,
    effectiveAreaMm2: 157,
    embedmentMinMm: 80,
    embedmentMaxMm: 240,
    steelYieldStrengthMpa: 500,
    steelUltimateStrengthMpa: 650,
    evaluation: {
      qualificationStandard: undefined,
    },
    source: '工具內建模板',
    notes: '未填入產品評估值前，黏結式錨栓只能做流程驗證與初篩。',
  },
]

export const defaultProject: ProjectCase = {
  id: 'current-project',
  name: '柱腳基板示例',
  ruleProfileId: 'tw_rc_112_anchor_profile',
  selectedProductId: 'generic-cast-m20',
  candidateProductIds: ['generic-cast-m20'],
  candidateLayoutVariants: [],
  auditTrail: [],
  updatedAt: new Date().toISOString(),
  layout: {
    concreteWidthMm: 420,
    concreteHeightMm: 420,
    thicknessMm: 500,
    concreteStrengthMpa: 28,
    maxAggregateSizeMm: 20,
    specifiedCoverRequirementMm: 40,
    crackedConcrete: true,
    lightweightConcrete: false,
    supplementaryReinforcement: false,
    shearHairpinReinforcement: false,
    basePlateBearingEnabled: false,
    basePlateLoadedAreaMm2: 0,
    basePlateLoadedWidthMm: 0,
    basePlateLoadedHeightMm: 0,
    basePlatePlanWidthMm: 0,
    basePlatePlanHeightMm: 0,
    basePlateSectionType: 'rectangle',
    basePlateSectionModulusXmm3: 0,
    basePlateSectionModulusYmm3: 0,
    basePlateSupportAreaMm2: 0,
    basePlateConfinedOnAllSides: false,
    basePlateConfinementMode: 'none',
    basePlateBearingMomentExternallyVerified: false,
    basePlateBendingEnabled: false,
    basePlateThicknessMm: 0,
    basePlateSteelYieldMpa: 250,
    basePlateCantileverXmm: 0,
    basePlateCantileverYmm: 0,
    columnSectionType: 'manual',
    columnDepthMm: 0,
    columnFlangeWidthMm: 0,
    columnCentroidOffsetXmm: 0,
    columnCentroidOffsetYmm: 0,
    anchorReinforcementEnabled: false,
    anchorReinforcementAreaMm2: 0,
    anchorReinforcementYieldMpa: 420,
    anchorReinforcementWithinHalfCa1: false,
    anchorReinforcementIntersectsEachAnchor: false,
    anchorReinforcementDevelopedForTension: false,
    anchorReinforcementDevelopedForShear: false,
    effectiveEmbedmentMm: 160,
    anchorCountX: 2,
    anchorCountY: 2,
    spacingXmm: 180,
    spacingYmm: 180,
    edgeLeftMm: 120,
    edgeRightMm: 120,
    edgeBottomMm: 120,
    edgeTopMm: 120,
  },
  loads: {
    tensionKn: 80,
    shearXKn: 18,
    shearYKn: 6,
    shearEccentricityXmm: 0,
    shearEccentricityYmm: 0,
    shearLeverArmMm: 0,
    shearAnchorCount: undefined,
    momentXKnM: 0,
    momentYKnM: 0,
    interactionEquation: 'linear',
    considerSeismic: false,
    seismicInputMode: 'total_design',
    designEarthquakeTensionKn: 0,
    designEarthquakeShearKn: 0,
    designEarthquakeShearXKn: 0,
    designEarthquakeShearYKn: 0,
    designEarthquakeMomentXKnM: 0,
    designEarthquakeMomentYKnM: 0,
    seismicDesignMethod: 'standard',
    overstrengthFactor: 1,
    ductileStretchLengthMm: 0,
    ductileBucklingRestrained: false,
    ductileAttachmentMechanismVerified: false,
    attachmentYieldTensionKn: 0,
    attachmentYieldShearKn: 0,
    attachmentYieldInteractionEquation: 'none',
    attachmentOverstrengthFactor: 1,
  },
  loadCases: [
    {
      id: 'load-case-1',
      name: 'LC1',
      loads: {
        tensionKn: 80,
        shearXKn: 18,
        shearYKn: 6,
        shearEccentricityXmm: 0,
        shearEccentricityYmm: 0,
        shearLeverArmMm: 0,
        shearAnchorCount: undefined,
        momentXKnM: 0,
        momentYKnM: 0,
        interactionEquation: 'linear',
        considerSeismic: false,
        seismicInputMode: 'total_design',
        designEarthquakeTensionKn: 0,
        designEarthquakeShearKn: 0,
        designEarthquakeShearXKn: 0,
        designEarthquakeShearYKn: 0,
        designEarthquakeMomentXKnM: 0,
        designEarthquakeMomentYKnM: 0,
        seismicDesignMethod: 'standard',
        overstrengthFactor: 1,
        ductileStretchLengthMm: 0,
        ductileBucklingRestrained: false,
        ductileAttachmentMechanismVerified: false,
        attachmentYieldTensionKn: 0,
        attachmentYieldShearKn: 0,
        attachmentYieldInteractionEquation: 'none',
        attachmentOverstrengthFactor: 1,
      },
    },
  ],
  activeLoadCaseId: 'load-case-1',
  loadPresetInput: {
    ...defaultLoadCasePresetInput,
    dead: {
      ...defaultLoadCasePresetInput.dead,
      tensionKn: 50,
      shearXKn: 8,
      shearYKn: 2,
    },
    live: {
      ...defaultLoadCasePresetInput.live,
      tensionKn: 25,
      shearXKn: 10,
      shearYKn: 4,
    },
    earthquake: {
      ...defaultLoadCasePresetInput.earthquake,
      tensionKn: 40,
      shearXKn: 16,
      shearYKn: 6,
    },
    overstrengthFactor: 2.5,
  },
  ui: defaultUnitPreferences,
  report: {
    ...defaultReportSettings,
  },
  documents: [],
}

export const presetProjects: ProjectCase[] = [
  defaultProject,
  {
    ...defaultProject,
    id: 'preset-expansion',
    name: '設備固定膨脹錨栓示例',
    selectedProductId: 'template-expansion-m16',
    layout: {
      ...defaultProject.layout,
      concreteWidthMm: 320,
      concreteHeightMm: 260,
      thicknessMm: 180,
      effectiveEmbedmentMm: 90,
      anchorCountX: 2,
      anchorCountY: 1,
      spacingXmm: 140,
      spacingYmm: 0,
      edgeLeftMm: 70,
      edgeRightMm: 110,
      edgeBottomMm: 90,
      edgeTopMm: 90,
    },
    loads: {
      ...defaultProject.loads,
      tensionKn: 18,
      shearXKn: 12,
      shearYKn: 0,
    },
    loadCases: [
      {
        id: 'load-case-1',
        name: 'LC1',
        loads: {
          ...defaultProject.loads,
          tensionKn: 18,
          shearXKn: 12,
          shearYKn: 0,
        },
      },
    ],
    activeLoadCaseId: 'load-case-1',
  },
  {
    ...defaultProject,
    id: 'preset-bonded',
    name: '化學錨栓補強示例',
    selectedProductId: 'template-bonded-m16',
    layout: {
      ...defaultProject.layout,
      concreteWidthMm: 360,
      concreteHeightMm: 360,
      thicknessMm: 260,
      effectiveEmbedmentMm: 140,
      anchorCountX: 1,
      anchorCountY: 2,
      spacingXmm: 0,
      spacingYmm: 150,
      edgeLeftMm: 110,
      edgeRightMm: 110,
      edgeBottomMm: 105,
      edgeTopMm: 105,
    },
    loads: {
      ...defaultProject.loads,
      tensionKn: 26,
      shearXKn: 4,
      shearYKn: 10,
    },
    loadCases: [
      {
        id: 'load-case-1',
        name: 'LC1',
        loads: {
          ...defaultProject.loads,
          tensionKn: 26,
          shearXKn: 4,
          shearYKn: 10,
        },
      },
    ],
    activeLoadCaseId: 'load-case-1',
  },
]
